[rgb]
# mode: effect | solid
mode = effect
# effect (built-in animations): aurora, flowing, neon, dreamy, sun,
#   cyberpunk, sunset, colorful, monster_woke
effect = aurora
# brightness: low | medium | high
brightness = high
# for mode = solid, set an RGB color (0-255):
r = 0
g = 255
b = 0
